<?php
$KEEUrl = get_option('siteurl') . '/wp-content/plugins/kaskus-emoticons/emoticons/';
$opt 	= get_option('kaskus_emoticons');

$KEReplace	= array(
	':ultah' => '<img src="'. $KEEUrl.'ultah.gif" style="border:none;background:none;" alt=":ultah" />',
	':kimpoi' => '<img src="'. $KEEUrl.'kimpoi.gif" style="border:none;background:none;" alt=":kimpoi" />',
	':bola' => '<img src="'. $KEEUrl.'bola.gif" style="border:none;background:none;" alt=":bola" />',
	':bedug' => '<img src="'. $KEEUrl.'lebaran02.gif" style="border:none;background:none;" alt=":bedug" />',
	':cool' => '<img src="'. $KEEUrl.'cool2.gif" style="border:none;background:none;" alt=":cool" />',
	':games' => '<img src="'. $KEEUrl.'games.gif" style="border:none;background:none;" alt=":games" />',
	':hn' => '<img src="'. $KEEUrl.'hotnews.gif" style="border:none;background:none;" alt=":hn" />',
	':ketupat' => '<img src="'. $KEEUrl.'lebaran02.gif" style="border:none;background:none;" alt=":ketupat" />',
	':maafagan' => '<img src="'. $KEEUrl.'lebaran01.gif" style="border:none;background:none;" alt=":maafagan" />',
	':maafaganwati' => '<img src="'. $KEEUrl.'lebaran04.gif" style="border:none;background:none;" alt=":maafaganwati" />',
	':salaman' => '<img src="'. $KEEUrl.'lebaran03.gif" style="border:none;background:none;" alt=":salaman" />',
	':salahkamar' => '<img src="'. $KEEUrl.'salah_kamar.gif" style="border:none;background:none;" alt=":salahkamar" />',



	':nohope' => '<img src="'. $KEEUrl.'nohope.gif" style="border:none;background:none;" alt=":nohope" />',
	':travel' => '<img src="'. $KEEUrl.'traveller.gif" style="border:none;background:none;" alt=":travel" />',
	':kr' => '<img src="'. $KEEUrl.'kaskus_radio.gif" style="border:none;background:none;" alt=":kr" />',
	':sorry' => '<img src="'. $KEEUrl.'sorry.gif" style="border:none;background:none;" alt=":sorry" />',
	':babygirl' => '<img src="'. $KEEUrl.'babygirl.gif" style="border:none;background:none;" alt=":babygirl" />',
	':babyboy1' => '<img src="'. $KEEUrl.'babyboy1.gif" style="border:none;background:none;" alt=":babyboy1" />',
	':babyboy' => '<img src="'. $KEEUrl.'babyboy.gif" style="border:none;background:none;" alt=":babyboy" />',
	':request' => '<img src="'. $KEEUrl.'request.gif" style="border:none;background:none;" alt=":request" />',


	':mewek' => '<img src="'. $KEEUrl.'mewek.gif" style="border:none;background:none;" alt=":mewek" />',
	':matabelo' => '<img src="'. $KEEUrl.'matabelo1.gif" style="border:none;background:none;" alt=":matabelo" />',
	':angel' => '<img src="'. $KEEUrl.'angel1.gif" style="border:none;background:none;" alt=":angel" />',
	':2thumbup' => '<img src="'. $KEEUrl.'jempol2.gif" style="border:none;background:none;" alt=":2thumbup" />',
	':thumbup' => '<img src="'. $KEEUrl.'jempol1.gif" style="border:none;background:none;" alt=":thumbup" />',
	':selamat' => '<img src="'. $KEEUrl.'selamat.gif" style="border:none;background:none;" alt=":selamat" />',
	':dp' => '<img src="'. $KEEUrl.'dp.gif" style="border:none;background:none;" alt=":dp" />',
	':cystg' => '<img src="'. $KEEUrl.'cystg.gif" style="border:none;background:none;" alt=":cystg" />',
	':hoax' => '<img src="'. $KEEUrl.'hoax.gif" style="border:none;background:none;" alt=":hoax" />',
	':toast' => '<img src="'. $KEEUrl.'toastcendol.gif" style="border:none;background:none;" alt=":toast" />',


	':cendol' => '<img src="'. $KEEUrl.'tambahan-kaskuser/cendol.gif" style="border:none;background:none;" alt=":cendol" />',

	':cd' => '<img src="'. $KEEUrl.'capede.gif" style="border:none;background:none;" alt=":cd" />',
	':hammer' => '<img src="'. $KEEUrl.'hammer.gif" style="border:none;background:none;" alt=":hammer" />',
	':peluk' => '<img src="'. $KEEUrl.'peluk.gif" style="border:none;background:none;" alt=":peluk" />',

	':malu2' => '<img src="'. $KEEUrl.'tambahan-kaskuser/malu2.gif" style="border:none;background:none;" alt=":malu2" />',
	':siul' => '<img src="'. $KEEUrl.'tambahan-kaskuser/siul.gif" style="border:none;background:none;" alt=":siul" />',
	':newyear' => '<img src="'. $KEEUrl.'tambahan-kaskuser/newyear.gif" style="border:none;background:none;" alt=":newyear" />',
	':alay' => '<img src="'. $KEEUrl.'tambahan-kaskuser/alay.gif" style="border:none;background:none;" alt=":alay" />',
	':hoax2' => '<img src="'. $KEEUrl.'tambahan-kaskuser/hoax.gif" style="border:none;background:none;" alt=":hoax2" />',
	':hope' => '<img src="'. $KEEUrl.'tambahan-kaskuser/hope.gif" style="border:none;background:none;" alt=":hope" />',
	':hotrit' => '<img src="'. $KEEUrl.'tambahan-kaskuser/hotrit.gif" style="border:none;background:none;" alt=":hotrit" />',
	':lapar' => '<img src="'. $KEEUrl.'tambahan-kaskuser/lapar.gif" style="border:none;background:none;" alt=":lapar" />',
	':mahongintip' => '<img src="'. $KEEUrl.'tambahan-kaskuser/mahongintip.gif" style="border:none;background:none;" alt=":mahongintip" />',
	':mewek2' => '<img src="'. $KEEUrl.'tambahan-kaskuser/mewek.gif" style="border:none;background:none;" alt=":mewek2" />',
	':nerd' => '<img src="'. $KEEUrl.'tambahan-kaskuser/nerd.gif" style="border:none;background:none;" alt=":nerd" />',
	':pertamax' => '<img src="'. $KEEUrl.'tambahan-kaskuser/pertamax.gif" style="border:none;background:none;" alt=":pertamax" />',
	':rate' => '<img src="'. $KEEUrl.'tambahan-kaskuser/rate.gif" style="border:none;background:none;" alt=":rate" />',
	':sungkem' => '<img src="'. $KEEUrl.'tambahan-kaskuser/sungkem.gif" style="border:none;background:none;" alt=":sungkem" />',
	':supermaho' => '<img src="'. $KEEUrl.'tambahan-kaskuser/supermaho.gif" style="border:none;background:none;" alt=":supermaho" />',
	':thanks2' => '<img src="'. $KEEUrl.'tambahan-kaskuser/thanks2.gif" style="border:none;background:none;" alt=":thanks2" />',
	':tkp' => '<img src="'. $KEEUrl.'tambahan-kaskuser/tkp.gif" style="border:none;background:none;" alt=":tkp" />',


	':cekpm' => '<img src="'. $KEEUrl.'cekpm.gif" style="border:none;background:none;" alt=":cekpm" />',
	':bingung' => '<img src="'. $KEEUrl.'bingung.gif" style="border:none;background:none;" alt=":bingung" />',
	':shakehand2' => '<img src="'. $KEEUrl.'shakehand2.gif" style="border:none;background:none;" alt=":shakehand2" />',
	':ngacir2' => '<img src="'. $KEEUrl.'ngacir2.gif" style="border:none;background:none;" alt=":ngacir2" />',
	':takut' => '<img src="'. $KEEUrl.'takut.gif" style="border:none;background:none;" alt=":takut" />',
	':recsel' => '<img src="'. $KEEUrl.'recseller.gif" style="border:none;background:none;" alt=":recsel" />',
	':ilovekaskus' => '<img src="'. $KEEUrl.'s_sm_ilovekaskus.gif" style="border:none;background:none;" alt=":ilovekaskus" />',
	':iloveindonesia' => '<img src="'. $KEEUrl.'I-Luv-Indonesia.gif" style="border:none;background:none;" alt=":iloveindonesia" />',
	':kiss' => '<img src="'. $KEEUrl.'cewek.gif" style="border:none;background:none;" alt=":kiss" />',
	':maho' => '<img src="'. $KEEUrl.'s_sm_maho.gif" style="border:none;background:none;" alt=":maho" />',
	':najis' => '<img src="'. $KEEUrl.'najis.gif" style="border:none;background:none;" alt=":najis" />',
	':nosara' => '<img src="'. $KEEUrl.'nosara.gif" style="border:none;background:none;" alt=":nosara" />',
	':marah' => '<img src="'. $KEEUrl.'marah.gif" style="border:none;background:none;" alt=":marah" />',
	':berduka' => '<img src="'. $KEEUrl.'berduka.gif" style="border:none;background:none;" alt=":berduka" />',
	':malu' => '<img src="'. $KEEUrl.'malu.gif" style="border:none;background:none;" alt=":malu" />',
	':ngakak' => '<img src="'. $KEEUrl.'ngakak.gif" style="border:none;background:none;" alt=":ngakak" />',
	':repost' => '<img src="'. $KEEUrl.'s_sm_repost1.gif" style="border:none;background:none;" alt=":repost" />',
	':repost2' => '<img src="'. $KEEUrl.'s_sm_repost2.gif" style="border:none;background:none;" alt=":repost2" />',
	':sup2:' => '<img src="'. $KEEUrl.'sundul.gif" style="border:none;background:none;" alt=":sup2:" />',
	':cendolbig' => '<img src="'. $KEEUrl.'s_big_cendol.gif" style="border:none;background:none;" alt=":cendolbig" />',
	':batabig' => '<img src="'. $KEEUrl.'s_big_batamerah.gif" style="border:none;background:none;" alt=":batabig" />',
	':jrb:' => '<img src="'. $KEEUrl.'fd_1.gif" style="border:none;background:none;" alt=":jrb:" />',
	':kts:' => '<img src="'. $KEEUrl.'fd_6.gif" style="border:none;background:none;" alt=":kts:" />',
	':sup:' => '<img src="'. $KEEUrl.'fd_5.gif" style="border:none;background:none;" alt=":sup:" />',
	':kbgt:' => '<img src="'. $KEEUrl.'fd_4.gif" style="border:none;background:none;" alt=":kbgt:" />',
	':kacau:' => '<img src="'. $KEEUrl.'fd_8.gif" style="border:none;background:none;" alt=":kacau:" />',
	':bigo:' => '<img src="'. $KEEUrl.'fd_3.gif" style="border:none;background:none;" alt=":bigo:" />',
	':repost:' => '<img src="'. $KEEUrl.'fd_7.gif" style="border:none;background:none;" alt=":repost:" />',
	':cd:' => '<img src="'. $KEEUrl.'fd_2.gif" style="border:none;background:none;" alt=":cd:" />',


	//small	
	':bata' => '<img src="'. $KEEUrl.'s_sm_batamerah.gif" style="border:none;background:none;" alt=":bata" />',
	':Yb' => '<img src="'. $KEEUrl.'s_sm_peace.gif" style="border:none;background:none;" alt=":Yb" />',
	':batas' => '<img src="'. $KEEUrl.'batas.gif" style="border:none;background:none;" alt=":batas" />',
	':cekpms' => '<img src="'. $KEEUrl.'cekpms.gif" style="border:none;background:none;" alt=":cekpms" />',
	':capedes' => '<img src="'. $KEEUrl.'capedes.gif" style="border:none;background:none;" alt=":capedes" />',
	':mahos' => '<img src="'. $KEEUrl.'mahos.gif" style="border:none;background:none;" alt=":mahos" />',
	':malus' => '<img src="'. $KEEUrl.'malus.gif" style="border:none;background:none;" alt=":malus" />',
	':kisss' => '<img src="'. $KEEUrl.'kisss.gif" style="border:none;background:none;" alt=":kisss" />',
	':ngakaks' => '<img src="'. $KEEUrl.'ngakaks.gif" style="border:none;background:none;" alt=":ngakaks" />',
	':takuts' => '<img src="'. $KEEUrl.'takuts.gif" style="border:none;background:none;" alt=":takuts" />',
	':reposts' => '<img src="'. $KEEUrl.'reposts.gif" style="border:none;background:none;" alt=":reposts" />',
	':hammers' => '<img src="'. $KEEUrl.'hammers.gif" style="border:none;background:none;" alt=":hammers" />',
	':sundulgans' => '<img src="'. $KEEUrl.'sundulgans.gif" style="border:none;background:none;" alt=":sundulgans" />',
	':mads' => '<img src="'. $KEEUrl.'mads.gif" style="border:none;background:none;" alt=":mads" />',
	':ilovekaskuss' => '<img src="'. $KEEUrl.'iluvkaskuss.gif" style="border:none;background:none;" alt=":ilovekaskuss" />',
	':najiss' => '<img src="'. $KEEUrl.'najiss.gif" style="border:none;background:none;" alt=":najiss" />',
	':berdukas' => '<img src="'. $KEEUrl.'berdukas.gif" style="border:none;background:none;" alt=":berdukas" />',
	':iloveindonesias' => '<img src="'. $KEEUrl.'iloveindonesias.gif" style="border:none;background:none;" alt=":iloveindonesias" />',
	':cendols' => '<img src="'. $KEEUrl.'cendols.gif" style="border:none;background:none;" alt=":cendols" />',
	':)b' => '<img src="'. $KEEUrl.'s_sm_smile.gif" style="border:none;background:none;" alt=":)b" />',
	':cendolb' => '<img src="'. $KEEUrl.'s_sm_cendol.gif" style="border:none;background:none;" alt=":cendolb" />',


	':berbusa:' => '<img src="'. $KEEUrl.'q20.gif" style="border:none;background:none;" alt=":berbusa:" />',
	':breakhear' => '<img src="'. $KEEUrl.'38.gif" style="border:none;background:none;" alt=":breakhear" />',
	':babi:' => '<img src="'. $KEEUrl.'27.gif" style="border:none;background:none;" alt=":babi:" />',
	':frog:' => '<img src="'. $KEEUrl.'frog.gif" style="border:none;background:none;" alt=":frog:" />',
	':D' => '<img src="'. $KEEUrl.'14.gif" style="border:none;background:none;" alt=":D" />',
	':Peace:' => '<img src="'. $KEEUrl.'005.gif" style="border:none;background:none;" alt=":Peace:" />',
	':thumbdown' => '<img src="'. $KEEUrl.'48.gif" style="border:none;background:none;" alt=":thumbdown" />',
	':metal:' => '<img src="'. $KEEUrl.'q17.gif" style="border:none;background:none;" alt=":metal:" />',
	':heart:' => '<img src="'. $KEEUrl.'37.gif" style="border:none;background:none;" alt=":heart:" />',
	':linux2:' => '<img src="'. $KEEUrl.'26.gif" style="border:none;background:none;" alt=":linux2:" />',
	':afro:' => '<img src="'. $KEEUrl.'kribo.gif" style="border:none;background:none;" alt=":afro:" />',
	':o' => '<img src="'. $KEEUrl.'07.gif" style="border:none;background:none;" alt=":o" />',
	':matabelo:' => '<img src="'. $KEEUrl.'004.gif" style="border:none;background:none;" alt=":matabelo:" />',
	':thumbup:' => '<img src="'. $KEEUrl.'47.gif" style="border:none;background:none;" alt=":thumbup:" />',
	':kissmouth' => '<img src="'. $KEEUrl.'36.gif" style="border:none;background:none;" alt=":kissmouth" />',
	':tabrakan:' => '<img src="'. $KEEUrl.'tabrakan.gif" style="border:none;background:none;" alt=":tabrakan:" />',
	':genit:' => '<img src="'. $KEEUrl.'q03.gif" style="border:none;background:none;" alt=":genit:" />',
	':linux1:' => '<img src="'. $KEEUrl.'25.gif" style="border:none;background:none;" alt=":linux1:" />',
	':hi:' => '<img src="'. $KEEUrl.'hi.gif" style="border:none;background:none;" alt=":hi:" />',
	':(' => '<img src="'. $KEEUrl.'06.gif" style="border:none;background:none;" alt=":(" />',
	':nohope:' => '<img src="'. $KEEUrl.'q11.gif" style="border:none;background:none;" alt=":nohope:" />',
	':siul:' => '<img src="'. $KEEUrl.'020.gif" style="border:none;background:none;" alt=":siul:" />',
	':norose:' => '<img src="'. $KEEUrl.'35.gif" style="border:none;background:none;" alt=":norose:" />',
	':malu:' => '<img src="'. $KEEUrl.'1.gif" style="border:none;background:none;" alt=":malu:" />',
	':army:' => '<img src="'. $KEEUrl.'24.gif" style="border:none;background:none;" alt=":army:" />',
	':fuck3:' => '<img src="'. $KEEUrl.'fuck-8.gif" style="border:none;background:none;" alt=":fuck3:" />',
	':)' => '<img src="'. $KEEUrl.'15.gif" style="border:none;background:none;" alt=":)" />',
	':Paws:' => '<img src="'. $KEEUrl.'paw.gif" style="border:none;background:none;" alt=":Paws:" />',
	':doctor:' => '<img src="'. $KEEUrl.'18.gif" style="border:none;background:none;" alt=":doctor:" />',
	':rose:' => '<img src="'. $KEEUrl.'34.gif" style="border:none;background:none;" alt=":rose:" />',
	':ngacir:' => '<img src="'. $KEEUrl.'ngacir.gif" style="border:none;background:none;" alt=":ngacir:" />',
	':confused:' => '<img src="'. $KEEUrl.'7.gif" style="border:none;background:none;" alt=":confused:" />',
	':angel:' => '<img src="'. $KEEUrl.'017.gif" style="border:none;background:none;" alt=":angel:" />',
	':fuck2:' => '<img src="'. $KEEUrl.'fuck-6.gif" style="border:none;background:none;" alt=":fuck2:" />',
	':kagets:' => '<img src="'. $KEEUrl.'3.gif" style="border:none;background:none;" alt=":kagets:" />',
	':tv:' => '<img src="'. $KEEUrl.'44.gif" style="border:none;background:none;" alt=":tv:" />',
	':medicine:' => '<img src="'. $KEEUrl.'33.gif" style="border:none;background:none;" alt=":medicine:" />',
	':fm:' => '<img src="'. $KEEUrl.'smileyfm329wj.gif" style="border:none;background:none;" alt=":fm:" />',
	':eek:' => '<img src="'. $KEEUrl.'4.gif" style="border:none;background:none;" alt=":eek:" />',
	':kissing:' => '<img src="'. $KEEUrl.'014.gif" style="border:none;background:none;" alt=":kissing:" />',
	':fuck:' => '<img src="'. $KEEUrl.'fuck-4.gif" style="border:none;background:none;" alt=":fuck:" />',
	':wowcantik' => '<img src="'. $KEEUrl.'001.gif" style="border:none;background:none;" alt=":wowcantik" />',
	':email:' => '<img src="'. $KEEUrl.'43.gif" style="border:none;background:none;" alt=":email:" />',
	':ricebowl:' => '<img src="'. $KEEUrl.'32.gif" style="border:none;background:none;" alt=":ricebowl:" />',
	':ck' => '<img src="'. $KEEUrl.'kaskuslove.gif" style="border:none;background:none;" alt=":ck" />',
	':mad:' => '<img src="'. $KEEUrl.'12.gif" style="border:none;background:none;" alt=":mad:" />',
	':hammer:' => '<img src="'. $KEEUrl.'8.gif" style="border:none;background:none;" alt=":hammer:" />',
	':flower:' => '<img src="'. $KEEUrl.'e03.gif" style="border:none;background:none;" alt=":flower:" />',
	':buldog:' => '<img src="'. $KEEUrl.'woof.gif" style="border:none;background:none;" alt=":buldog:" />',
	':clock:' => '<img src="'. $KEEUrl.'42.gif" style="border:none;background:none;" alt=":clock:" />',
	':coffee:' => '<img src="'. $KEEUrl.'31.gif" style="border:none;background:none;" alt=":coffee:" />',
	':amazed:' => '<img src="'. $KEEUrl.'amazed.gif" style="border:none;background:none;" alt=":amazed:" />',
	':rolleyes:' => '<img src="'. $KEEUrl.'01.gif" style="border:none;background:none;" alt=":rolleyes:" />',
	':sun:' => '<img src="'. $KEEUrl.'008.gif" style="border:none;background:none;" alt=":sun:" />',
	':rainbow:' => '<img src="'. $KEEUrl.'e02.gif" style="border:none;background:none;" alt=":rainbow:" />',
	':bikini:' => '<img src="'. $KEEUrl.'vana-bum-vanaweb-dot-com.gif" style="border:none;background:none;" alt=":bikini:" />',
	':Phone:' => '<img src="'. $KEEUrl.'41.gif" style="border:none;background:none;" alt=":Phone:" />',
	':baby:' => '<img src="'. $KEEUrl.'30.gif" style="border:none;background:none;" alt=":baby:" />',
	':gila:' => '<img src="'. $KEEUrl.'crazy.gif" style="border:none;background:none;" alt=":gila:" />',
	':cool:' => '<img src="'. $KEEUrl.'05.gif" style="border:none;background:none;" alt=":cool:" />',
	':moon:' => '<img src="'. $KEEUrl.'007.gif" style="border:none;background:none;" alt=":moon:" />',
	':rain:' => '<img src="'. $KEEUrl.'60.gif" style="border:none;background:none;" alt=":rain:" />',
	':tai:' => '<img src="'. $KEEUrl.'shit-3.gif" style="border:none;background:none;" alt=":tai:" />',
	':present:' => '<img src="'. $KEEUrl.'40.gif" style="border:none;background:none;" alt=":present:" />',
	':anjing:' => '<img src="'. $KEEUrl.'29.gif" style="border:none;background:none;" alt=":anjing:" />',
	':kimpoi:' => '<img src="'. $KEEUrl.'smiley_couple.gif" style="border:none;background:none;" alt=":kimpoi:" />',
	':p' => '<img src="'. $KEEUrl.'6.gif" style="border:none;background:none;" alt=":p" />',
	':think:' => '<img src="'. $KEEUrl.'006.gif" style="border:none;background:none;" alt=":think:" />',
	':exclamati' => '<img src="'. $KEEUrl.'52.gif" style="border:none;background:none;" alt=":exclamati" />',
	':Onigiri:' => '<img src="'. $KEEUrl.'rice.gif" style="border:none;background:none;" alt=":Onigiri:" />',
	':table:' => '<img src="'. $KEEUrl.'39.gif" style="border:none;background:none;" alt=":table:" />',
	':kucing:' => '<img src="'. $KEEUrl.'28.gif" style="border:none;background:none;" alt=":kucing:" />',
	':beer:' => '<img src="'. $KEEUrl.'smiley_beer.gif" style="border:none;background:none;" alt=":beer:" />',
	';)' => '<img src="'. $KEEUrl.'13.gif" style="border:none;background:none;" alt=";)" />',
	':shutup:' => '<img src="'. $KEEUrl.'5.gif" style="border:none;background:none;" alt=":shutup:" />',
	':shakehand' => '<img src="'. $KEEUrl.'49.gif" style="border:none;background:none;" alt=":shakehand" />',
	':bingung:' => '<img src="'. $KEEUrl.'bolakbalik.gif" style="border:none;background:none;" alt=":bingung:" />'         
);
$KEReplace2 = $KEReplace;
if(isset($opt['stat'])){
	foreach($opt['stat'] as $k=>$v){
		$KEReplace[$k]="";
	}
}
?>